Fix missing positional argument in docker build
Fixes:

	$ docker build -f docker/sink_service/Dockerfile -t local/my_sink_service:tag1
	ERROR: docker: 'docker buildx build' requires 1 argument

	Usage:  docker buildx build [OPTIONS] PATH | URL | -

	Run 'docker buildx build --help' for more information